// Generated by CoffeeScript 1.10.0
(function() {
  this.PlayersList = new Mongo.Collection('players');

  if (Meteor.isClient) {
    Template.leaderboard.helpers({
      'player': function() {
        return PlayersList.find({}, {
          sort: {
            score: -1,
            name: 1
          }
        });
      },
      'selectedClass': function() {
        var playerId, selectedPlayer;
        playerId = this._id;
        selectedPlayer = Session.get('selectedPlayer');
        if (playerId === selectedPlayer) {
          return "selected";
        }
      },
      'selectedPlayer': function() {
        var selectedPlayer;
        selectedPlayer = Session.get('selectedPlayer');
        return PlayersList.findOne({
          _id: selectedPlayer
        });
      }
    });
    Template.leaderboard.events({
      'click .player': function() {
        var playerId;
        playerId = this._id;
        return Session.set('selectedPlayer', playerId);
      },
      'click .increment': function() {
        var selectedPlayer;
        selectedPlayer = Session.get('selectedPlayer');
        return PlayersList.update({
          _id: selectedPlayer
        }, {
          $inc: {
            score: 5
          }
        });
      },
      'click .decrement': function() {
        var selectedPlayer;
        selectedPlayer = Session.get('selectedPlayer');
        return PlayersList.update({
          _id: selectedPlayer
        }, {
          $inc: {
            score: -5
          }
        });
      },
      'click .remove': function() {
        var selectedPlayer;
        selectedPlayer = Session.get('selectedPlayer');
        return PlayersList.remove({
          _id: selectedPlayer
        });
      }
    });
    Template.addPlayerForm.events({
      'submit form': function(event) {
        var playerNameVar;
        event.preventDefault();
        playerNameVar = event.target.playerName.value;
        console.log(playerNameVar);
        PlayersList.insert({
          name: playerNameVar,
          score: 0
        });
        return event.target.playerName.value = "";
      }
    });
  }

  if (Meteor.isServer) {
    console.log("Hello Server!?!?!");
  }

}).call(this);
